FROM node:22-alpine
RUN apk add --no-cache git
RUN git config --global user.name "AuthorGit AutoSave" && \
    git config --global user.email "bot@authorgit.local"
WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .

# Run with --watch for auto-reloading during development
CMD ["node", "--watch", "server.js"]
